# Generated by Django 4.2.1 on 2023-06-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Base_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrador',
            name='Perfil_for',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.user_perfil'),
        ),
    ]
