# Generated by Django 4.2.1 on 2023-06-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_perfil_id_decompra'),
        ('Base_register', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrador',
            name='Perfil_for',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.user_perfil'),
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='register_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_register.cobrador'),
        ),
    ]
