# Generated by Django 4.2.1 on 2023-06-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0004_alter_months_people_alter_months_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuyente',
            name='register_for',
        ),
        migrations.RemoveField(
            model_name='months',
            name='people',
        ),
        migrations.RemoveField(
            model_name='months',
            name='years',
        ),
        migrations.RemoveField(
            model_name='pagosfijos',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pagosfijos',
            name='negocio',
        ),
        migrations.RemoveField(
            model_name='pagosfijos',
            name='people',
        ),
        migrations.RemoveField(
            model_name='pagosfijos',
            name='years',
        ),
        migrations.RemoveField(
            model_name='updatemonthscontry',
            name='update',
        ),
        migrations.DeleteModel(
            name='Cobrador',
        ),
        migrations.DeleteModel(
            name='Contribuyente',
        ),
        migrations.DeleteModel(
            name='Months',
        ),
        migrations.DeleteModel(
            name='pagosFijos',
        ),
        migrations.DeleteModel(
            name='typeNegocio',
        ),
        migrations.DeleteModel(
            name='typePagos',
        ),
        migrations.DeleteModel(
            name='UpdateMonthsContry',
        ),
        migrations.DeleteModel(
            name='Years',
        ),
    ]
