# Generated by Django 4.2.1 on 2023-06-25 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0007_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='contryUnique',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_register.contribuyente'),
        ),
    ]
