# Generated by Django 4.2.1 on 2023-07-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0008_alter_ordering_contryunique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagosfijos',
            name='name',
        ),
    ]
