# Generated by Django 4.2.1 on 2023-07-09 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0014_remove_pagosfijos_negocio_remove_pagosfijos_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContryBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Negocio', models.CharField(blank=True, max_length=50)),
                ('IMI', models.CharField(blank=True, max_length=50)),
                ('Basura', models.CharField(blank=True, max_length=50)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.contribuyente')),
            ],
        ),
        migrations.CreateModel(
            name='pagosFijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=10)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.cuentacontrybasic')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.contribuyente')),
            ],
        ),
    ]
