# Generated by Django 4.2.1 on 2023-08-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0017_remove_cuentacontrybasic_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontrybasic',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
