# Generated by Django 4.2.1 on 2023-08-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0018_cuentacontrybasic_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
