# Generated by Django 4.2.1 on 2023-08-08 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0026_remove_pagosfijos_negocio_remove_pagosfijos_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagosFijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresas', models.CharField(max_length=255)),
                ('Pagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.pagocuenta')),
            ],
        ),
    ]
