# Generated by Django 4.2.1 on 2023-08-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0027_pagosfijos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_empresa', models.CharField(max_length=255)),
                ('Direcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='pagosFijos',
        ),
        migrations.AddField(
            model_name='pagocuenta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_register.empresa'),
        ),
    ]
