# Generated by Django 4.2.1 on 2023-06-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0003_alter_cobrador_perfil_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.contribuyente'),
        ),
        migrations.AlterField(
            model_name='months',
            name='years',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.years'),
        ),
        migrations.AlterField(
            model_name='pagosfijos',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.typepagos', unique=True),
        ),
        migrations.AlterField(
            model_name='pagosfijos',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.typenegocio', unique=True),
        ),
        migrations.AlterField(
            model_name='pagosfijos',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.contribuyente', unique=True),
        ),
        migrations.AlterField(
            model_name='pagosfijos',
            name='years',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.years', unique=True),
        ),
        migrations.AlterField(
            model_name='updatemonthscontry',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.months'),
        ),
    ]
