# Generated by Django 4.2.1 on 2023-06-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abs', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('CH', 'CH'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=2)),
                ('primer_apellido', models.CharField(blank=True, max_length=100)),
                ('complete_name', models.IntegerField(blank=True, null=True)),
                ('id_type_abs', models.IntegerField()),
                ('id_primer_apellido', models.IntegerField()),
                ('id_complete_name', models.IntegerField()),
                ('contryUnique', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_register.cobrador')),
            ],
        ),
    ]
