# Generated by Django 4.2.1 on 2023-07-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0011_cuentacontrybasic_alter_pagosfijos_negocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacontrybasic',
            name='Basura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cuentacontrybasic',
            name='IMI',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cuentacontrybasic',
            name='Negocio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
