# Generated by Django 4.2.1 on 2023-08-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0015_cuentacontrybasic_pagosfijos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontrybasic',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
