# Generated by Django 4.2.1 on 2023-08-01 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0016_cuentacontrybasic_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacontrybasic',
            name='activo',
        ),
    ]
