# Generated by Django 4.2.1 on 2023-08-04 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0019_cuentaspagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('data_at', models.DateField(auto_now_add=True)),
                ('contribuyente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_register.contribuyente')),
                ('cuenta_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_register.cuentaspagos')),
            ],
        ),
    ]
