# Generated by Django 4.2.1 on 2023-08-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0020_pagocuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocuenta',
            name='contribuyente',
        ),
        migrations.RemoveField(
            model_name='pagocuenta',
            name='cuenta_pago',
        ),
        migrations.DeleteModel(
            name='CuentasPagos',
        ),
        migrations.DeleteModel(
            name='PagoCuenta',
        ),
    ]
