# Generated by Django 4.2.1 on 2023-08-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0022_cuentaspagos_pagocuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaspagos',
            name='code_max',
            field=models.CharField(max_length=21),
        ),
    ]
