# Generated by Django 4.2.1 on 2023-08-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0024_alter_cuentaspagos_code_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaspagos',
            name='p_year',
            field=models.BooleanField(default=False, help_text='este campo solo se aplica en pagos anuales'),
        ),
    ]
