# Generated by Django 4.2.1 on 2023-08-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0025_cuentaspagos_p_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagosfijos',
            name='negocio',
        ),
        migrations.RemoveField(
            model_name='pagosfijos',
            name='people',
        ),
        migrations.DeleteModel(
            name='CuentaContryBasic',
        ),
        migrations.DeleteModel(
            name='pagosFijos',
        ),
    ]
