# Generated by Django 4.2.1 on 2023-08-08 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_register', '0028_empresa_delete_pagosfijos_pagocuenta_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocuenta',
            name='contribuyente',
        ),
        migrations.RemoveField(
            model_name='pagocuenta',
            name='cuenta_pago',
        ),
        migrations.RemoveField(
            model_name='pagocuenta',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='PagoCuenta',
        ),
    ]
