# Generated by Django 4.2.1 on 2023-06-08 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_perfil',
            name='ID_DECOMPRA',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
